package id.ac.ui.cs.advprog.mysawit.harvest.error;

public enum HarvestErrorKey {
    HARVEST_ALREADY_SUBMITTED_TODAY,
    NO_PHOTOS_PROVIDED,
    PHOTO_TOO_LARGE,
    INVALID_PHOTO_TYPE,
    VALIDATION_FAILED,
    INVALID_DATE_RANGE,
    INVALID_STATUS_VALUE,
    BURUH_NOT_ASSIGNED_TO_MANDOR,
    MANDOR_NOT_AUTHORIZED,
    USER_NOT_FOUND,
    USER_NOT_BURUH,
    FORBIDDEN,
    STORAGE_ERROR
}